FROM sgrio/build-agent:1.0.3

RUN apt-get update && apt-get install -y \
      ca-certificates \
      curl \
      gnupg \
      lsb-release && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-compose-plugin \
      supervisor && \
    rm -rf /var/lib/apt/lists/*

COPY supervisor/ /etc/supervisor/conf.d/
ADD docker-entrypoint.d/ /docker-entrypoint.d/

VOLUME /var/lib/docker

CMD ["cat"]
